### ISSUE TITLE
Data de divulgação dos resultados.

### ISSUE THREAD

**Issue by GuiPretto** [penseadvance/front-end-intern-test#2]
Olá, meu nome é Guilherme, sou um dos candidatos à vaga de estágio em desenvolvimento front-end e tenho uma dúvida que gostaria de tirar. 
Já se passou 1 semana desde a data de envio dos links dos projetos no GitHub, mas não houve nenhuma resposta até o momento, e não há informações sobre datas em outros locais. Sendo assim, gostaria de demonstrar o meu interessa com essa vaga perguntando se tem uma data prévia de divulgação de resultados ou se ao menos a avaliação está em processo e ainda irá divulgar o resultado. Pois estou preocupado com a possibilidade de eu ter passado ou não e não estar sabendo disso.
Por fim, obrigado pela atenção e disposição em ler essa mensagem.

**Comment by lucas-varela** [comment]
Hey, Guilherme!

Em resumo: pretendemos enviar o resultado do teste a todos os candidatos até quarta-feira, dia 4. Vamos fazer isso por email e dar um pequeno feedback sobre o teste independentemente do resultado, por isso essa pequena demora. 

Abrimos 3 vagas de desenvolvimento ao mesmo tempo e mais de 100 candidatos enviaram testes para elas. Digamos que nós subestimamos um pouco o trabalho que teríamos corrigindo esses testes 👀

Pedimos desculpa por não termos sido mais claros em relação ao prazo e como entraríamos em contato após o envio do teste. Com certeza deixaremos isso mais claro em vagas futuras. E agradecemos por criar essa issue, vai servir de informação para outros candidatos.

Qualquer outra dúvida, conta com a gente :)

**Comment by GuiPretto** [comment]
Muito obrigado pela resposta e pelo tempo usado para responder essa issue, compreendo totalmente a quantidade de trabalho e agradeço pela resposta rápida. ^^
